name: syntax check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read 

concurrency:
  group: shellcheck-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  self-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display the info
        run: echo "$ZSH_NAME" "$ZSH_VERSION"
        shell: zsh {0}
      - name: Run self check
        run: zsh -n 'sobole.zsh-theme'
        shell: zsh {0}
