name: shellcheck

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: shellcheck-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: --shell bash
        with:
          severity: style
          check_together: 'yes'
          additional_files: 'sobole.zsh-theme'

  self-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Display the info
        run: echo "$ZSH_NAME" "$ZSH_VERSION"
        shell: zsh {0}
        
      - name: Run self check
        run: zsh -n 'sobole.zsh-theme'
        shell: zsh {0}
